name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Compile the program
      run: gcc main.c -o kasir-app

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: kasir-app
        path: kasir-app
