name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install GCC
      run: sudo apt-get update && sudo apt-get install -y gcc

    - name: Compile the program
      run: gcc -o simple-kasir main.c

    - name: Run the program
      run: ./simple-kasir
